name: CV application

on:
  push:
    branches: 
      - dev
  

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest] 
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest tox tox-gh-actions
        pip install -r requirements.txt
    - name: Test with tox
      run: tox
      
  lint:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Super-Linter
      uses: github/super-linter@v4.10.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
