name: Template-CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_call:
    inputs:
      REGION:
        type: string        
      MICROSERVICES:
        type: string         
      ASSUME_ROLE:
        type: string         
      ASSUME_ROLE_PROD:
        type: string         
      EXCLUDED_CLASS:
        type: string                
      PLATFORM_REPO:
        type: string        
      BUILD_PATH:
        type: string         
      JAVA_HOME:
        type: string        
      MAVEN_HOME:
        type: string      
    
env:
  ## Sets environment variable
  JAVA_HOME: ${{inputs.JAVA_HOME}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run scanner for the repository
        continue-on-error: true
        run: |
          whispers ${{ github.workspace }} > whispers.txt
          .github/workflows/scripts/whispers.sh  
          
               
      - name: Maven Build(crm-dev)
        if: ${{ contains(env.BRANCH, 'crm-dev') }}
        run: ${{inputs.MAVEN_HOME}}/bin/mvn clean deploy -U -s settings.xml  -Dunobank-artifactory-url=https://nexus.dev.ph.unobank.asia/repository/ -Drelease-repo=dev-maven-releases -Dsnapshot-repo=dev-maven-snapshots -Dartifactory-username=admin -Dartifactory-password=25abd83a-d558-45bd-8fe0-c3bee99dd608
        working-directory: ${{inputs.BUILD_PATH}}
        
      - name: Maven Build(crm-sit)
        if: contains(env.BRANCH, 'crm-sit')
        run: ${{inputs.MAVEN_HOME}}/bin/mvn clean deploy -U -s settings.xml  -Dunobank-artifactory-url=https://nexus.dev.ph.unobank.asia/repository/ -Drelease-repo=sit-maven-releases -Dsnapshot-repo=sit-maven-snapshots -Dartifactory-username=admin -Dartifactory-password=25abd83a-d558-45bd-8fe0-c3bee99dd608
        working-directory: ${{inputs.BUILD_PATH}}
        
      - name: Maven Build(crm-uat)
        if: contains(env.BRANCH, 'crm-uat')
        run: ${{inputs.MAVEN_HOME}}/bin/mvn clean deploy -U -s settings.xml  -Dunobank-artifactory-url=https://nexus.dev.ph.unobank.asia/repository/ -Drelease-repo=uat-maven-releases -Dsnapshot-repo=uat-maven-snapshots -Dartifactory-username=admin -Dartifactory-password=25abd83a-d558-45bd-8fe0-c3bee99dd608
        working-directory: ${{inputs.BUILD_PATH}}
        
      - name: Maven Build(crm-prod)
        if: contains(env.BRANCH, 'crm-prod')
        run: ${{inputs.MAVEN_HOME}}/bin/mvn clean deploy -U -s settings.xml  -Dunobank-artifactory-url=https://nexus.dev.ph.unobank.asia/repository/ -Drelease-repo=dev-maven-releases -Dsnapshot-repo=dev-maven-snapshots -Dartifactory-username=admin -Dartifactory-password=25abd83a-d558-45bd-8fe0-c3bee99dd608
        working-directory: ${{inputs.BUILD_PATH}}
        
      - name: Maven Build(loans-dev)
        if: contains(env.BRANCH, 'loans-dev')
        run: ${{inputs.MAVEN_HOME}}/bin/mvn clean deploy -U -s settings.xml  -Dunobank-artifactory-url=https://nexus.dev.ph.unobank.asia/repository/ -Drelease-repo=dev-maven-releases -Dsnapshot-repo=dev-maven-snapshots -Dartifactory-username=admin -Dartifactory-password=25abd83a-d558-45bd-8fe0-c3bee99dd608
        working-directory: ${{inputs.BUILD_PATH}}
        
      - name: Maven Build(loans-sit)
        if: contains(env.BRANCH, 'loans-sit')
        run: ${{inputs.MAVEN_HOME}}/bin/mvn clean deploy -U -s settings.xml  -Dunobank-artifactory-url=https://nexus.dev.ph.unobank.asia/repository/ -Drelease-repo=sit-maven-releases -Dsnapshot-repo=sit-maven-snapshots -Dartifactory-username=admin -Dartifactory-password=25abd83a-d558-45bd-8fe0-c3bee99dd608
        working-directory: ${{inputs.BUILD_PATH}}
        
      - name: Maven Build(loans-uat)
        if: contains(env.BRANCH, 'loans-uat')
        run: ${{inputs.MAVEN_HOME}}/bin/mvn clean deploy -U -s settings.xml  -Dunobank-artifactory-url=https://nexus.dev.ph.unobank.asia/repository/ -Drelease-repo=uat-maven-releases -Dsnapshot-repo=uat-maven-snapshots -Dartifactory-username=admin -Dartifactory-password=25abd83a-d558-45bd-8fe0-c3bee99dd608
        working-directory: ${{inputs.BUILD_PATH}}
        
      - name: Maven Build(loans-prod)
        if: contains(env.BRANCH, 'loans-prod')
        run: ${{inputs.MAVEN_HOME}}/bin/mvn clean deploy -U -s settings.xml  -Dunobank-artifactory-url=https://nexus.dev.ph.unobank.asia/repository/ -Drelease-repo=dev-maven-releases -Dsnapshot-repo=dev-maven-snapshots -Dartifactory-username=admin -Dartifactory-password=25abd83a-d558-45bd-8fe0-c3bee99dd608
        working-directory: ${{inputs.BUILD_PATH}}
        

      - name: SonarQube Scan
        uses: unobankasia/sonarqube-action-1@v1.2.1
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectBaseDir: ./
          projectKey: ${{inputs.MICROSERVICES}}
          binaries: target/classes
          exclusions: ${{inputs.EXCLUDED_CLASS}}
      
      - name: SonarQube Quality Gate check
        continue-on-error: true
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        with:
         scanMetadataReportFile: .scannerwork/report-task.txt
      
      
